name: Build AnimeActors app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=12.0

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore "AnimeActors.sln"
      
    - name: Retrieve the secret and decode it to a file
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        echo $KEYSTORE_BASE64 | base64 --decode > Yuki.keystore

    - name: Build
      env:
        KEYSTORE_STOREPASS: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_KEYALIAS: ${{ secrets.KEYSTORE_KEYALIAS }}
        KEYSTORE_KEYPASS: ${{ secrets.KEYSTORE_KEYPASS }}
      run: msbuild "AnimeActors.sln" /t:AnimeActors_Android:SignAndroidPackage /p:Configuration=Release;AndroidKeyStore=True;AndroidSigningKeyStore=Yuki.keystore;AndroidSigningStorePass=$KEYSTORE_KEYALIAS;AndroidSigningKeyAlias=$KEYSTORE_KEYALIAS;AndroidSigningKeyPass=$KEYSTORE_KEYPASS 
